### PR TITLE
Dependency Updates and Vulnerability Fixes

### PR DESCRIPTION
**Pull request by TheJoshuaEvans**
## Motivation
This PR aims to fix dependency vulnerabilities found when attempting to use this cli with newer versions of node / npm

## Test Plan

No actual code was altered, save for changing references of `os.tmpDir` to `os.tmpdir` as the tmpDir function is depreciated. All existing tests pass

### CODE REVIEW

**Comment by TheJoshuaEvans** [comment]
I think babel isn't doing what it's supposed to - the modules in the `lib` folder is still using classes

**Comment by TheJoshuaEvans** [comment]
## Note
This update increases the minimum recommended node version to 6.0. This is in line with the current (as of December 20th, 2018) LTS schedule for Node.js. Node versions <6 are no longer supported and should not be used in general

**Comment by TheJoshuaEvans** [comment]
@SecurityInsanity Can you please review

**Comment by SecurityInsanity** [comment]
Hey @TheJoshuaEvans ,

I'm not on the team that maintains this anymore so although it looks fine to me, I won't be able to herald it through. That being said I'm going to get someone to review this as we speak. Sorry for the delay, and thank you for contributing!

**Comment by aaronlangford31** [comment]
Hey Josh,

Thanks for taking the time to help improve this repo.

So the babel changes were to fix some errors you were seeing in compile/test? Do you mind providing some detail on those errors?

-Aaron

**Pull request merged**
